parameters:
    secret_key: '%env(SECRET_KEY)%'
    client_id: '%env(CLIENT_ID)%'
    redirect_uri: '%env(REDIRECT_URI)%'
    upload_dir: '%kernel.project_dir%/public/uploads'

framework:
    http_client: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\PaymentWebhookController:
        arguments:
            $secretKey: '%secret_key%'
            $clientId: '%client_id%'
            $redirectUri: '%redirect_uri%'

    App\EventListener\ValidationExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }
    App\Services\FileService:
        arguments:
            $uploadDir: '%upload_dir%'

#    Normalizer
    App\Serializer\Normalizer\UserNormalizer:
        tags:
            - { name: 'serializer.normalizer' }
    App\Serializer\Normalizer\SellerNormalizer:
        tags:
            - { name: 'serializer.normalizer' }
