lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'  # Путь к приватному ключу
    public_key: '%kernel.project_dir%/config/jwt/public.pem'   # Путь к публичному ключу
